[plugins]
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "0.3.0" }
publishPlugin = { id = "com.gradle.plugin-publish", version = "0.19.0" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "10.2.1" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.19.0" }

